#!/bin/sh
# Tool to send alert by name.
if [ "$1" = "" ]; then
  echo "usage: $0 alertName" 1>&2
  exit 1
fi

RESULT=$(curl -s "http://localhost:4030/sendAlert?alert=$1")
if [ "$RESULT" = "Error sending Alert" ] ; then
    echo "Failed to send alert, check spelling"
    exit 2
elif [ -z "$RESULT" ] ; then
    echo "Failed to send request, service up?"
    exit 3
elif [ "$RESULT" != "OK" ] ; then
    echo "Unknown error : $RESULT"
    exit 4
fi

echo "OK"